spring:
  application:
    name: uMag
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5443/umag
    password: password
    username: okointellect
  flyway:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  rabbitmq:
    username: user
    password: pass
    addresses: 0.0.0.0:5672
    queuename: umagQueue
    allQueueName: umagAllQueue
server:
  port: ${SERVER_PORT:8008}
  forward-headers-strategy: framework