version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
            RABBITMQ_DEFAULT_PASS: pass
            RABBITMQ_DEFAULT_USER: user
    ports:
        - 5672:5672
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge